version: '3.1'

services:

  db:
    image: mysql:5.7.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
